//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ile_cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Egitimlerim
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string AltBaslik_1 { get; set; }
        public string AltBaslik_2 { get; set; }
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
